### ISSUE TITLE
Removal of Appendix A and adding Warning

### ISSUE THREAD

**Issue by sakimura** [peppelinux/federation-wallet#21]
Salve, Giuseppe! 

In today's AB/C call, we have spent almost full hour discussing the adoption of this draft. 
The quicker way to go forward is 

a) remove Appendix A and post it either as an issue or something (so that it will not be lost); and 
b) add a warning upfront, like in the FAPI drafts, so that people not familiar with the OpenID Process will not regard the draft as something they can assume is not changing, etc., as a precaution. This is in response to Joseph's concern that people in Europe tend to read the specs in the openid.net as reliable. 

Warning text that FAPI specs are putting (well, it is just following ISO text in that respect ...)

**Warning**
This document is not an OIDF International Standard. It is distributed for review and comment. It is subject to change without notice and may not be referred to as an International Standard.

**Comment by peppelinux** [comment]
The metadata parameters definitions are temporary moved to this issue: https://github.com/peppelinux/federation-wallet/issues/22
