### ISSUE TITLE
Custodial vs non-custodial for Mobile Wallet Native Application

### ISSUE THREAD

**Issue by surfnet-niels** [peppelinux/federation-wallet#4]
Also with a 'Mobile Wallet Native Application' implementations there may not be a clear distinction between custodial and non-custodial. The key is in that case partially stored on the users device and partially in a HSM. As an example of a real life system (Yivi/IRMA) that used this approach: https://privacybydesign.foundation/irma-explanation/

From their site:
"Credentials are cryptographically bound to a mobile phone, and to each other, via a personal secret cryptographic key. This private key is crucial for the security of the Yivi app; it must be stored securely. Such secure local storage is difficult on a mobile phone, since the device may be rooted or hacked. That is why a small but crucial part of this private key is stored outside the phone on a so-called keyshare-server that is operated by the Privacy by Design foundation. The Yivi PIN code is checked by the keyshare server, see the [more detailed explanations](https://privacybydesign.foundation/irma-start/#hood) elsewhere. Only when the PIN checks out, will the server participate with its own small part of the secret personal key, and can attributes be disclosed. The keyshare sever will not see the attributes themselves, nor to whom they are disclosed."

**Comment by peppelinux** [comment]
I'm prone to introduce a middle color between those two, enabling such hybrid solution you briefly described.

if a PR would be produced by you @surfnet-niels in the meanwhile, that would be appreciated and supported by me

**Comment by surfnet-niels** [comment]
The issue hinges on the definition of custodial. In the Yivi example, the provider on its own has no ability to decrypt the credentials on its own, so without user participation. That would suggest a non-custodial wallet. The wallet provider could however prevent the user from gaining access to their wallet credentials by not providing their part of the key material. However, there are several other reasons this might also happen. This fact alone does probably not change the fundamental architectual principal of custodial vs non-custodial.
