### ISSUE TITLE
"Third-Party Trust" or "Trusted Third Party"

### ISSUE THREAD

**Issue by surfnet-niels** [peppelinux/federation-wallet#5]
I am wondering if the naming "Third-Party Trust" might not yield association with Third-Party cookies. Perhaps just name this "Trusted Third Party" (as also mentioned in the explain)

**Comment by peppelinux** [comment]
the subject is the trust model and the scope of the term in discussion is the definition of the trust model type

for this reason "third-party" represents the type and "trust model" the subject of the type, therefore "third party trust model"

with this issue we open a conversation about what would be the best name and if we want to change this term for a better alternative
