### ISSUE TITLE
Wallet Provider as part of TA?

### ISSUE THREAD

**Issue by surfnet-niels** [peppelinux/federation-wallet#6]
"All entities, including the Credential Issuer, Holder, and Relying Party, are underpinned by the Trust Anchor, which provides a foundational layer of trust and security for the entire system." 
Should this not also mention the Wallet Provider?

**Comment by peppelinux** [comment]
Yes it should, the suggestion that aims to resolve this: https://github.com/peppelinux/federation-wallet/pull/9/files#r1720831223

**Comment by selfissued** [comment]
Fixed by #9
